services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: another_backend
    ports:
      - "5432:5432"
  # app:
  #   build: .
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     DATABASE_URL: postgresql://root:root@db:5432/another_backend
  #     NODE_ENV: production
  #     JWT_SECRET: ${JWT_SECRET}
  #     RESEND_API_KEY: ${RESEND_API_KEY}
  #     CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
  #     CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
  #     CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
  #     PORT: 3333
